(defun sumar ()
(+ (read) (read)))
(defun restar ()
(- (read) (read)))
(defun multiplicar ()
(* (read) (read)))
(defun dividir ()
(/ (read) (read)))

(print "Ingrese dos numeros para sumar")
(sumar)
(print "Ingrese dos numeros para restar")
(restar)
(print "Ingrese dos numeros para multiplicar")
(multiplicar)
(print "Ingrese dos numeros para dividir")
(dividir)